### ISSUE TITLE
Unify transformers/tables/files definition order. Currently it is different

### ISSUE THREAD

**Issue by ikalinin1** [vividus-framework/vividus#3389]
In addition to logging I would suggest to unify transformers/tables/files definition order. Currently it is different, viz.:
```
Examples:
{transformer=FROM_DB, dbKey=testdb, sqlQuery=$\{sql-all-category-product-last-flag\}}
{transformer=FILTERING, byMaxRows=$\{filter-products\}}
```
and
```
Examples:
{transformer=FILTERING, column.category=.*lipstick.*}
/tables/vime/photo_p${index}.table
```
Initial source is on the opposite sides of the list

_Originally posted by @GrimA9e in https://github.com/vividus-framework/vividus/issues/3291#issuecomment-1291746894_

**Comment by valfirst** [comment]
The order is always the same:
- loading table defined after all transformers (in the first example the table is empty),
- apply transformers to the table from top to bottom.

The first case:
- load empty table
- load data from DB and merge it with empty table
- filter the table from the previous step

The second case:
- load table from the specified resource path
- filter to table

The root cause of the misunderstanding is users don't see by their eyes this empty table from the first case, it might be confusing, I guess, but the logic is always the same.
