### ISSUE TITLE
Mozilla Firefox: 'Apply' button is not clicked though visible and only one on the page

### ISSUE THREAD

**Issue by VolhaHoman** [vividus-framework/vividus#639]
**Describe the bug**
'Apply' button is not clicked, while is visible by xPath and is unique on UI. Though the line above is clicked instead of the button.

FF version 76.0.1 (64-bit)
OS Windows 10 Enterprise v.1903
Vividus version 0.2.4-SNAPSHOT

[PERF Board - Mozilla Firefox 2020-06-01 12-18-44.zip](https://github.com/vividus-framework/vividus/files/4710907/PERF.Board.-.Mozilla.Firefox.2020-06-01.12-18-44.zip)

**Comment by VitaliLebedzeu** [comment]
@VolhaHoman 
After a deep investigating of this issue, I can say that the "Apply" button is not able to be clicked because when you use the step "When I click on element located by("XPath to your element")" for choosing the project from the list, some of the required variables aren't setting. That does not allow you to click on the "Apply" button.
This issue was noticed only with firefox web driver. I am able to suggest you use the next workaround

```
When I execute sequence of actions:
|type   |argument                                          |
|CLICK |By.xpath("XPath to your element")])|
```

With this solution, I was able to achieve the successful execution tests how on Chrome as on Firefox. 
This solution was checked locally and using the Selenium standalone server docker image.

**Comment by VolhaHoman** [comment]
Thank you
