### ISSUE TITLE
[composite files,  jbehave] Composite files are skipped if comment is present in Composite

### ISSUE THREAD

**Issue by AlenaSikorskaya** [vividus-framework/vividus#649]
Currently  if there is a comment in Composite steps are skipped after the comment.

Comments like these:
!-- bug #
!-- a When I ....

![image](https://user-images.githubusercontent.com/58731281/83670162-6b9b9280-a5db-11ea-8eff-c70dfb4d0949.png)

**Comment by AlenaSikorskaya** [comment]
p4

**Comment by valfirst** [comment]
The fix is implemented in JBehave, see https://jbehave.atlassian.net/browse/JBEHAVE-1414.
New JBehave version containing the fix was integrated in #746.

The example of the composite step with the comment was provided in #754. As for the ignored step the example will be the same, the difference is the content after `!--`.
